### ISSUE TITLE
fail_cb option

### ISSUE THREAD

**Issue by mche** [benvanstaveren/Mojolicious-Plugin-Authentication#19]
Hi!

About config options.

Good option fail_render=>{...}.

But the option  fail_cb => sub {my ($r, $c, $captures, $arg) = @_; ....}
will be more powerfull.

Isn`t it?

**Comment by jjatria** [comment]
The changes in the [`fail_sub`](https://github.com/benvanstaveren/Mojolicious-Plugin-Authentication/tree/fail_sub) branch implement something that does this. It makes it so that the `fail_render` option can take either a hash ref, or a sub ref that itself returns a hash ref. 

The subroutine would only be called when there is no valid response, and the return value would be discarded unless it was true. If valid, the returned hash reference would be dereferenced and passed to `$c->render`, to keep the current interface.

What do you think?

**Comment by mche** [comment]
Ok, could be closed
